apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fqpq06p8n-java-springboot
  janus-idp.io/tekton: fqpq06p8n-java-springboot
  backstage.io/kubernetes-id: fqpq06p8n-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fqpq06p8n-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
